# Generated by Django 4.1.7 on 2024-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_contact_email_contact_is_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isystem_in_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_count', models.IntegerField(default=0)),
                ('teachers_count', models.IntegerField(default=0)),
                ('projects_count', models.IntegerField(default=0)),
            ],
        ),
    ]
