# Generated by Django 4.1.7 on 2024-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_isystem_in_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isystem_in_numbers',
            name='course_count',
            field=models.CharField(default=0, max_length=212),
        ),
        migrations.AlterField(
            model_name='isystem_in_numbers',
            name='projects_count',
            field=models.CharField(default=0, max_length=212),
        ),
        migrations.AlterField(
            model_name='isystem_in_numbers',
            name='teachers_count',
            field=models.CharField(default=0, max_length=212),
        ),
    ]
